# Generated by Django 5.1 on 2024-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smrWeb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="musician",
        ),
        migrations.AddField(
            model_name="musician",
            name="albums",
            field=models.ManyToManyField(to="smrWeb.album"),
        ),
    ]
